#!/usr/bin/env bash
# Check OAuth consent screen publishing status

set -euo pipefail

PROJECT_ID="inboximp-email-triage"

echo "======================================================================"
echo "CHECKING OAUTH CONSENT SCREEN PUBLISHING STATUS"
echo "======================================================================"
echo ""

echo "Please open this URL and check the Publishing status:"
echo ""
echo "👉 https://console.cloud.google.com/apis/credentials/consent?project=${PROJECT_ID}"
echo ""
echo "Look for 'Publishing status' at the top of the page."
echo ""
echo "What does it say?"
echo ""
echo "Option 1: 'Testing'"
echo "  - Only test users can use the app"
echo "  - EVEN WITH proper scopes, Gmail API may restrict usage"
echo "  - Solution: Publish the app OR complete verification"
echo ""
echo "Option 2: 'In production' (not verified)"
echo "  - Anyone can use the app"
echo "  - BUT restricted scopes (Gmail) are LIMITED until verified"
echo "  - Solution: Complete Google's verification process"
echo ""
echo "Option 3: 'In production' (verified)"
echo "  - Fully functional for all users"
echo "  - No restrictions"
echo ""
echo "======================================================================"
echo ""
echo "If status is 'Testing', try clicking 'PUBLISH APP' button."
echo "This may fix the issue without requiring full verification."
echo ""
echo "If it asks for verification, you have two choices:"
echo "  A. Complete verification (takes 1-2 weeks)"
echo "  B. Keep in Testing mode and only use with test users"
echo ""
echo "======================================================================"
echo ""
echo "IMPORTANT: Gmail API has extra restrictions for restricted scopes"
echo ""
echo "Even if:"
echo "  ✓ OAuth grants the token with all scopes"
echo "  ✓ Google recognizes the scopes (we confirmed this)"
echo "  ✓ You're a test user"
echo "  ✓ Scopes are configured correctly"
echo ""
echo "Gmail API can STILL block the request if:"
echo "  ✗ App is in 'Testing' mode (not Published)"
echo "  ✗ App is Published but not Verified for restricted scopes"
echo ""
echo "This is Google's extra layer of protection for sensitive APIs."
echo ""
echo "======================================================================"
echo ""
read -p "What is your current Publishing status? (Testing/In production): " STATUS

if [[ "${STATUS}" == "Testing" ]] || [[ "${STATUS}" == "testing" ]]; then
    echo ""
    echo "Your app is in TESTING mode. This is likely the problem!"
    echo ""
    echo "Gmail API restricts apps in Testing mode even for test users."
    echo ""
    echo "SOLUTION: Publish the app"
    echo ""
    echo "1. Go to the OAuth consent screen"
    echo "2. Click 'PUBLISH APP' button"
    echo "3. You may see a warning about verification"
    echo "4. Click 'Publish' anyway (you can verify later if needed)"
    echo ""
    echo "After publishing:"
    echo "  - Revoke access: https://myaccount.google.com/permissions"
    echo "  - Re-authorize at http://localhost:8000"
    echo "  - Test viewing an email"
    echo ""
elif [[ "${STATUS}" == "In production" ]] || [[ "${STATUS}" == "in production" ]] || [[ "${STATUS}" == "Production" ]]; then
    echo ""
    echo "Your app is in PRODUCTION mode."
    echo ""
    read -p "Does it show as 'Verified' or 'Needs verification'? " VERIFIED

    if [[ "${VERIFIED}" == "Needs verification" ]] || [[ "${VERIFIED}" == "needs verification" ]]; then
        echo ""
        echo "App is Published but NOT VERIFIED for restricted scopes."
        echo ""
        echo "This means Gmail API may still restrict usage."
        echo ""
        echo "SOLUTIONS:"
        echo ""
        echo "Option A: Complete verification (recommended for production)"
        echo "  1. Click 'Prepare for verification' button"
        echo "  2. Fill out the verification form"
        echo "  3. Submit for review (takes 1-2 weeks)"
        echo ""
        echo "Option B: Use Service Account with Domain-Wide Delegation (Workspace only)"
        echo "  - Bypasses OAuth consent entirely"
        echo "  - Requires Google Workspace admin access"
        echo ""
    else
        echo ""
        echo "App is Published AND Verified!"
        echo ""
        echo "This should work. The issue might be:"
        echo "  1. Cached authorization (try revoking and re-authorizing)"
        echo "  2. Account-level security policy"
        echo "  3. Need to wait a few minutes for changes to propagate"
        echo ""
    fi
fi

echo ""
echo "======================================================================"
