"""
Centralised configuration for the email triage service.

Populate these values instead of exporting environment variables.
"""

# Gmail configuration -------------------------------------------------------

# List the Gmail inboxes you want to monitor.
GMAIL_ACCOUNTS = [
    "alexsheppert@gmail.com",
    # Add more accounts here.
]

# Path to the OAuth client secret JSON. The bootstrap script auto-detects
# client_secret_desktop.json, but you can override it here if needed.
GMAIL_CLIENT_SECRET_PATH = "client_secret_desktop.json"

# Directory containing the per-account token JSON files generated by
# bootstrap_gmail_token.py.
GMAIL_OAUTH_TOKEN_DIR = ".gmail_tokens"

# Pub/Sub topic used for Gmail push notifications.
GMAIL_TOPIC_NAME = "projects/email-assistant-475201/topics/email-triage"

# Optional: override the delegated user when using a service account.
GMAIL_DELEGATED_USER = None

# Optional: service account JSON for domain-wide delegation.
GMAIL_SERVICE_ACCOUNT_FILE = None

# Optional: custom classification prompt path.
CLASSIFICATION_PROMPT_PATH = "classification_prompt.txt"


# Supabase configuration ----------------------------------------------------

# Set these once your Supabase project is ready.
SUPABASE_URL = "https://wxliwwdftbolaxnpjjaj.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4bGl3d2RmdGJvbGF4bnBqamFqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDQ5NzE4MiwiZXhwIjoyMDc2MDczMTgyfQ.ES_jW6reSFNh7kwk3ZyEyKbbQ3M7ThZWMXV7f9XcRjs"

# Optional: anon key if you need client-side access later.
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4bGl3d2RmdGJvbGF4bnBqamFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0OTcxODIsImV4cCI6MjA3NjA3MzE4Mn0.kjfy_CM-x4uX38JuN3B_3Hr30j0B_wgULudc0kRkiKs"


# Telegram configuration ----------------------------------------------------
# Leave these as None to fall back to keys.py or environment variables.
TELEGRAM_BOT_TOKEN = None
TELEGRAM_CHAT_ID = None
