#!/usr/bin/env bash
# Test script for localhost:8000 diagnostic
# Run this to collect diagnostic information about the metadata-only error

set -euo pipefail

echo "======================================================================"
echo "LOCALHOST DIAGNOSTIC TEST"
echo "======================================================================"
echo ""
echo "This script will help diagnose the metadata-only permission issue."
echo ""
echo "Prerequisites:"
echo "1. You must be running the app on localhost:8000"
echo "2. You must be signed in to the web UI"
echo ""
echo "----------------------------------------------------------------------"
echo "STEP 1: Start the server with enhanced logging"
echo "----------------------------------------------------------------------"
echo ""
echo "Run this command in a separate terminal:"
echo ""
echo "  EMAIL_TRIAGE_LOG_LEVEL=DEBUG python3 -m uvicorn app:app --host 0.0.0.0 --port 8000 --log-level debug"
echo ""
echo "----------------------------------------------------------------------"
echo "STEP 2: Reproduce the error"
echo "----------------------------------------------------------------------"
echo ""
echo "1. Go to http://localhost:8000"
echo "2. Sign in with your Google account"
echo "3. Navigate to your inbox"
echo "4. Click 'View' on any email"
echo "5. You should see: 'Mailbox token only grants gmail.metadata...'"
echo ""
echo "----------------------------------------------------------------------"
echo "STEP 3: Check the server logs for DIAGNOSTIC messages"
echo "----------------------------------------------------------------------"
echo ""
echo "Look for these log lines (they should appear when you click 'View'):"
echo ""
echo "1. DIAGNOSTIC: Building Gmail service for alexsheppert@gmail.com using token source: ..."
echo "   → Shows whether using 'supabase' or 'filesystem' token"
echo ""
echo "2. DIAGNOSTIC: Loading token for alexsheppert@gmail.com from SUPABASE with X scopes: [...]"
echo "   → Shows which scopes the loaded token has"
echo ""
echo "3. DIAGNOSTIC: Fetching message XXX for alexsheppert@gmail.com with scopes: [...]"
echo "   → Shows the actual scopes being used for the Gmail API call"
echo ""
echo "4. DIAGNOSTIC: Gmail API error when fetching XXX for alexsheppert@gmail.com - Status=403, Error=..."
echo "   → Shows the EXACT error message from Gmail API"
echo ""
echo "----------------------------------------------------------------------"
echo "STEP 4: Copy the diagnostic output"
echo "----------------------------------------------------------------------"
echo ""
echo "Copy ALL lines containing 'DIAGNOSTIC' and send them to me."
echo ""
echo "Example output to look for:"
echo ""
cat << 'EOF'
INFO: DIAGNOSTIC: Loading token for alexsheppert@gmail.com from SUPABASE with 3 scopes: ['gmail.modify', 'gmail.readonly', 'gmail.metadata']
INFO: DIAGNOSTIC: Building Gmail service for alexsheppert@gmail.com using token source: supabase, scopes: [...]
INFO: DIAGNOSTIC: Fetching message 193e5f... for alexsheppert@gmail.com with scopes: ['https://www.googleapis.com/auth/gmail.modify', ...] (valid=True, expired=False)
ERROR: DIAGNOSTIC: Gmail API error when fetching 193e5f... for alexsheppert@gmail.com - Status=403, Error={"error": {"code": 403, "message": "Request had insufficient authentication scopes.", "errors": [...] }}
EOF
echo ""
echo "======================================================================"
echo "ALTERNATIVE: Check if it's a Google OAuth Consent Verification Issue"
echo "======================================================================"
echo ""
echo "Gmail scopes (gmail.modify, gmail.readonly) are 'restricted' by Google."
echo "For unverified apps, these restrictions apply:"
echo ""
echo "1. Only 'test users' can grant these scopes"
echo "2. Even if consent is granted, Google may restrict API calls"
echo "3. Apps must complete OAuth consent screen verification"
echo ""
echo "To check:"
echo "1. Go to: https://console.cloud.google.com/apis/credentials/consent?project=inboximp-email-triage"
echo "2. Check 'Publishing status'"
echo "3. Check if alexsheppert@gmail.com is listed as a test user"
echo ""
echo "If status is 'Testing' and you're NOT a test user:"
echo "  → This is likely your issue!"
echo "  → Solution: Add alexsheppert@gmail.com as a test user"
echo ""
echo "If status is 'In production' but app is not verified:"
echo "  → Google may be blocking restricted scopes"
echo "  → Solution: Complete OAuth verification OR add users as test users"
echo ""
echo "======================================================================"
