name: Deploy via Script

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for Workload Identity Federation
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/561574736348/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-deployer@inboximp-email-triage.iam.gserviceaccount.com'

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy + Verify (verify_e2e.py)
        run: |
          python3 verify_e2e.py \
            --use-active-gcloud \
            --region us-central1 \
            --service email-triage \
            --subscription email-triage-push
